root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  entrypoint = ["./tmp/api"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "migrations", "deploy", ".git"]
  delay = 200
