// internal/server/server.go
package server

import (
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/yogisaka/nexqia-api/docs" // swagger spec, generated by `make swag-generate` — import registers it with swag's global spec registry
	"github.com/yogisaka/nexqia-api/internal/auth"
	"github.com/yogisaka/nexqia-api/internal/config"
	"github.com/yogisaka/nexqia-api/internal/mfa"
	"github.com/yogisaka/nexqia-api/internal/ratelimit"
	"github.com/yogisaka/nexqia-api/internal/version"
)

func NewRouter(pool *pgxpool.Pool, redisClient *redis.Client, cfg config.Config) *gin.Engine {
	router := gin.Default()
	router.GET("/healthz", HealthzHandler)
	router.GET("/version", VersionHandler)
	// Public for now — auth on the docs page itself is deferred, see README.
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	limiter := ratelimit.NewLimiter(redisClient)
	hasher := auth.NewPasswordHasher(
		cfg.PasswordHashMaxConcurrent,
		time.Duration(cfg.PasswordHashQueueTimeoutMS)*time.Millisecond,
		auth.Argon2Params{
			MemoryKiB:   cfg.Argon2MemoryKiB,
			Iterations:  cfg.Argon2Iterations,
			Parallelism: cfg.Argon2Parallelism,
		},
	)

	// Fails fast on startup if MFA_SECRET_ENCRYPTION_KEY isn't valid base64/32 bytes —
	// same fail-fast posture as mustGetEnv in internal/config.
	enc, err := mfa.NewEncryptorFromBase64(cfg.MFASecretEncryptionKey)
	if err != nil {
		panic(err)
	}

	v1 := router.Group("/api/v1")

	// Public, pre-tenant-context: resolves a company code before X-Company-ID is known
	// (see docs/design/specs/2026-09-16-his-auth-wiring-design.md §3).
	RegisterCompanyLookupRoute(v1, pool)
	v1.POST("/auth/register", RegisterHandler(pool, cfg, hasher, limiter))

	// Merchant isn't known yet on these routes (spec §3a) — company-scoped RLS only.
	companyOnly := v1.Group("", CompanyOnlyMiddleware(pool))
	companyOnly.POST("/auth/login", LoginHandler(cfg.JWTSecret, limiter, cfg, hasher, enc, redisClient))
	companyOnly.POST("/auth/select-merchant", SelectMerchantHandler(cfg.JWTSecret, cfg, redisClient))
	// Keep-alive (nexqia-his KeepAlive.tsx) also hits /auth/refresh, not a
	// separate endpoint — a duplicate /auth/heartbeat existed briefly but was
	// functionally identical and let a caller accidentally bypass the
	// frontend's single-flight refresh dedup (see apiClient.ts refreshOnce).
	companyOnly.POST("/auth/refresh", RefreshHandler(cfg))
	companyOnly.POST("/auth/logout", LogoutHandler(cfg))

	// Merchant isn't known yet on these routes either (same reasoning as
	// companyOnly above) — but these DO need auth, unlike login/refresh.
	// See docs/design/specs/2026-09-23-saas-registration-owner-bootstrap-design.md §3.
	companyOnlyAuthed := v1.Group("", CompanyOnlyMiddleware(pool), AuthMiddleware(cfg.JWTSecret), RateLimitAPIMiddleware(limiter, cfg))
	RegisterCompanyLevelRoutes(companyOnlyAuthed, cfg)

	tenant := v1.Group("", TenantMiddleware(pool))
	protected := tenant.Group("", AuthMiddleware(cfg.JWTSecret), RateLimitAPIMiddleware(limiter, cfg))

	// Pin management/unlock must stay reachable while locked — deliberately not
	// behind AppLockMiddleware (spec §6).
	RegisterPinRoutes(protected, hasher, redisClient, cfg)

	locked := protected.Group("", AppLockMiddleware(redisClient, cfg))
	locked.GET("/ping", PingHandler)
	locked.POST("/auth/switch-merchant", SwitchMerchantHandler(cfg))
	locked.GET("/auth/sessions", ListSessionsHandler)
	locked.DELETE("/auth/sessions/:id", RevokeSessionHandler)
	RegisterTenancyRoutes(locked)
	RegisterMRNConfigRoutes(locked)
	RegisterDiagnosisConfigRoutes(locked)
	RegisterRBACRoutes(locked, hasher)
	RegisterMFARoutes(locked, enc, hasher)
	RegisterPersonRoutes(locked, cfg)
	RegisterPersonFamilyRoutes(locked)
	RegisterPatientAllergyRoutes(locked)
	RegisterTerminologyRoutes(locked)
	RegisterDepartmentRoutes(locked)
	RegisterTariffRoutes(locked)
	RegisterPayerRoutes(locked)
	RegisterPhysicianRoutes(locked)
	RegisterPhysicianScheduleRoutes(locked)
	RegisterCounterRoutes(locked)
	RegisterQueueRoutes(locked)
	RegisterAdmissionRoutes(locked)
	RegisterDisplayRoutes(locked)

	platform := v1.Group("/platform", PlatformTxMiddleware(pool))
	RegisterPlatformRoutes(platform, limiter, cfg, hasher)

	return router
}

// HealthzHandler godoc
// @Summary Liveness check
// @Tags system
// @Produce json
// @Success 200 {object} object
// @Router /healthz [get]
func HealthzHandler(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// VersionHandler godoc
// @Summary Build version
// @Tags system
// @Produce json
// @Success 200 {object} object
// @Router /version [get]
func VersionHandler(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"version": version.Version})
}

// PingHandler godoc
// @Summary Check active tenant context
// @Description Returns the company_id/merchant_id bound to the current session — sanity check after login/switch-merchant.
// @Tags system
// @Produce json
// @Security BearerAuth
// @Param X-Merchant-ID header string true "Active merchant UUID"
// @Success 200 {object} apiResponse
// @Router /ping [get]
func PingHandler(c *gin.Context) {
	tx := TxFromContext(c)
	var companyID, merchantID string
	err := tx.QueryRow(c.Request.Context(),
		"SELECT current_setting('app.current_company_id'), current_setting('app.current_merchant_id')",
	).Scan(&companyID, &merchantID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"data": gin.H{"company_id": companyID, "merchant_id": merchantID},
		"meta": gin.H{},
	})
}
