ALTER DEFAULT PRIVILEGES IN SCHEMA operations REVOKE USAGE, SELECT ON SEQUENCES FROM app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA operations REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_runtime;
REVOKE USAGE ON SCHEMA operations FROM app_runtime;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA operations FROM app_runtime;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA operations FROM app_runtime;