ALTER DEFAULT PRIVILEGES IN SCHEMA terminology REVOKE USAGE, SELECT ON SEQUENCES FROM app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE USAGE, SELECT ON SEQUENCES FROM app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA terminology REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_runtime;
REVOKE USAGE ON SCHEMA core, terminology FROM app_runtime;
DROP ROLE app_runtime;
