// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CoreAccessLog struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	ActorID    pgtype.UUID
	Resource   string
	ResourceID pgtype.UUID
	Action     string
	IpAddress  *netip.Addr
	CreatedAt  pgtype.Timestamptz
}

type CoreAppUser struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	PersonID     pgtype.UUID
	Username     string
	Email        pgtype.Text
	PasswordHash string
	MfaSecret    pgtype.Text
	IsActive     bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.UUID
	RowVersion   int32
	PinHash      pgtype.Text
	Phone        pgtype.Text
}

type CoreAuditLog struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	TableName  string
	RecordID   pgtype.UUID
	Action     string
	OldValue   []byte
	NewValue   []byte
	ChangedBy  pgtype.UUID
	ChangedAt  pgtype.Timestamptz
}

type CoreBed struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	WardID     pgtype.UUID
	Code       string
	Status     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	DeletedBy  pgtype.UUID
	RowVersion int32
}

type CoreCompany struct {
	ID                    pgtype.UUID
	Code                  string
	Name                  string
	IsActive              bool
	CreatedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedAt             pgtype.Timestamptz
	UpdatedBy             pgtype.UUID
	DeletedAt             pgtype.Timestamptz
	DeletedBy             pgtype.UUID
	RowVersion            int32
	MaxConcurrentSessions int32
}

type CoreDepartment struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	MerchantID         pgtype.UUID
	Code               string
	Name               string
	SpecialtyConceptID pgtype.UUID
	IsActive           bool
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	DeletedBy          pgtype.UUID
	RowVersion         int32
}

type CoreDietType struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	MerchantID     pgtype.UUID
	Code           string
	Name           string
	DefaultCalorie pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
	RowVersion     int32
}

type CoreFeatureFlag struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	FlagKey    string
	FlagValue  []byte
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	RowVersion int32
}

type CoreManufacturer struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	MerchantID   pgtype.UUID
	Code         string
	Name         string
	Abbreviation pgtype.Text
	Address      pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	RowVersion   int32
}

type CoreMediaLink struct {
	ID         pgtype.UUID
	MediaID    pgtype.UUID
	OwnerTable string
	OwnerID    pgtype.UUID
	Purpose    string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	DeletedBy  pgtype.UUID
}

type CoreMedium struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	MerchantID       pgtype.UUID
	StorageProvider  string
	StorageKey       string
	OriginalFilename string
	MimeType         string
	SizeBytes        int64
	ChecksumSha256   string
	Status           string
	VirusScanStatus  string
	Metadata         []byte
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	DeletedBy        pgtype.UUID
	RowVersion       int32
}

type CoreMerchant struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	Code               string
	Name               string
	KemkesFacilityCode pgtype.Text
	BpjsPpkCode        pgtype.Text
	Timezone           string
	IsActive           bool
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	DeletedBy          pgtype.UUID
	RowVersion         int32
}

type CoreMrnConfig struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	Format     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
}

type CoreDiagnosisConfig struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	CodeSystem string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
}

type CoreMfaRecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type CoreNotification struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	MerchantID     pgtype.UUID
	Channel        string
	ReferenceTable pgtype.Text
	ReferenceID    pgtype.UUID
	Message        string
	Payload        []byte
	IsRead         bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
}

type CorePatientAllergy struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	PersonID      pgtype.UUID
	AllergyType   string
	SubstanceName string
	Reaction      pgtype.Text
	Severity      pgtype.Text
	IsActive      bool
	RecordedAt    pgtype.Timestamptz
	RecordedBy    pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	RowVersion    int32
	EffectSide    pgtype.Text
	EventDate     pgtype.Date
}

type CorePayer struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	Code       string
	Name       string
	PayerType  string
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	DeletedBy  pgtype.UUID
	RowVersion int32
}

type CorePayerServiceRule struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	MerchantID      pgtype.UUID
	PayerID         pgtype.UUID
	ServiceItemID   pgtype.UUID
	RuleType        string
	DiscountPercent pgtype.Numeric
	DiscountAmount  pgtype.Numeric
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	RowVersion      int32
}

type CorePermission struct {
	ID          pgtype.UUID
	Code        string
	Description string
	Module      string
}

type CorePerson struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	Nik                    pgtype.Text
	MedicalRecordNo        pgtype.Text
	FullName               string
	BirthDate              pgtype.Date
	BirthPlace             pgtype.Text
	Gender                 pgtype.Text
	BloodType              pgtype.Text
	MaritalStatus          pgtype.Text
	ReligionConceptID      pgtype.UUID
	EducationConceptID     pgtype.UUID
	EthnicityConceptID     pgtype.UUID
	Phone                  pgtype.Text
	Email                  pgtype.Text
	Address                pgtype.Text
	CreatedAt              pgtype.Timestamptz
	CreatedBy              pgtype.UUID
	UpdatedAt              pgtype.Timestamptz
	UpdatedBy              pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	DeletedBy              pgtype.UUID
	RowVersion             int32
	FamilyID               pgtype.UUID
	PhotoUrl               pgtype.Text
	NikSearchHash          pgtype.Text
	RegionVillageConceptID pgtype.UUID
	CitizenshipConceptID   pgtype.UUID
	IdentityTypeConceptID  pgtype.UUID
	JobConceptID           pgtype.UUID
	MaritalStatusConceptID pgtype.UUID
	BloodTypeConceptID     pgtype.UUID
}

type CorePersonFamily struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	PersonID               pgtype.UUID
	FullName               string
	Phone                  pgtype.Text
	Email                  pgtype.Text
	BirthDate              pgtype.Date
	BirthPlace             pgtype.Text
	Gender                 pgtype.Text
	Address                pgtype.Text
	RegionVillageConceptID pgtype.UUID
	PostalCode             pgtype.Text
	RelationshipConceptID  pgtype.UUID
	PositionConceptID      pgtype.UUID
	JobConceptID           pgtype.UUID
	IsResponsiblePerson    bool
	CreatedAt              pgtype.Timestamptz
	CreatedBy              pgtype.UUID
	UpdatedAt              pgtype.Timestamptz
	UpdatedBy              pgtype.UUID
	DeletedAt              pgtype.Timestamptz
	DeletedBy              pgtype.UUID
	RowVersion             int32
}

type CorePersonMergeLog struct {
	ID                pgtype.UUID
	SurvivingPersonID pgtype.UUID
	MergedPersonID    pgtype.UUID
	Reason            pgtype.Text
	MergedAt          pgtype.Timestamptz
	MergedBy          pgtype.UUID
}

type CorePhysician struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	MerchantID         pgtype.UUID
	PersonID           pgtype.UUID
	StrNumber          pgtype.Text
	SipNumber          pgtype.Text
	SpecialtyConceptID pgtype.UUID
	IsActive           bool
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	DeletedBy          pgtype.UUID
	RowVersion         int32
}

type CoreRateComponent struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	Code       string
	Name       string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	DeletedBy  pgtype.UUID
	RowVersion int32
}

type CoreRefreshToken struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CompanyID   pgtype.UUID
	MerchantID  pgtype.UUID
	DeviceID    string
	DeviceLabel string
	TokenHash   string
	IssuedAt    pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedIp   netip.Addr
}

type CoreRole struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	Name                  string
	Description           pgtype.Text
	IsSystem              bool
	RequiresPhysicianData bool
	CreatedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedAt             pgtype.Timestamptz
	UpdatedBy             pgtype.UUID
	DeletedAt             pgtype.Timestamptz
	DeletedBy             pgtype.UUID
	RowVersion            int32
}

type CoreRolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type CoreServiceItem struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	MerchantID pgtype.UUID
	Code       string
	Name       string
	ItemType   string
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	DeletedBy  pgtype.UUID
	RowVersion int32
}

type CoreServiceRate struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	MerchantID      pgtype.UUID
	ServiceItemID   pgtype.UUID
	RateComponentID pgtype.UUID
	PayerClass      string
	Amount          pgtype.Numeric
	EffectiveFrom   pgtype.Date
	EffectiveTo     pgtype.Date
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
	DeletedAt       pgtype.Timestamptz
	DeletedBy       pgtype.UUID
	RowVersion      int32
}

type CoreSupplier struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	MerchantID        pgtype.UUID
	Code              string
	Name              string
	PicName           pgtype.Text
	PicPhone          pgtype.Text
	Address           pgtype.Text
	Npwp              pgtype.Text
	BankAccount       []byte
	CreditLimit       pgtype.Numeric
	LeadTimeDays      pgtype.Int4
	LeadTimeCitoDays  pgtype.Int4
	PaymentTermDays   pgtype.Int4
	ContractStartDate pgtype.Date
	ContractEndDate   pgtype.Date
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	DeletedAt         pgtype.Timestamptz
	DeletedBy         pgtype.UUID
	RowVersion        int32
}

type CoreUserMerchantRole struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	MerchantID pgtype.UUID
	RoleID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
}

type CoreWard struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	MerchantID   pgtype.UUID
	DepartmentID pgtype.UUID
	Code         string
	Name         string
	WardClass    pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.UUID
	RowVersion   int32
}

type OperationsAdmission struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	MerchantID         pgtype.UUID
	VisitNo            string
	PersonID           pgtype.UUID
	AdmissionType      string
	DepartmentID       pgtype.UUID
	PhysicianID        pgtype.UUID
	WardID             pgtype.UUID
	BedID              pgtype.UUID
	PrimaryPayerID     pgtype.UUID
	BpjsSepNumber      pgtype.Text
	Status             string
	AdmissionAt        pgtype.Timestamptz
	DischargeAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	DeletedBy          pgtype.UUID
	RowVersion         int32
	Complaint          pgtype.Text
	ReferralSource     pgtype.Text
	Note               pgtype.Text
	DiagnosisText      pgtype.Text
	TreatmentBarriers  pgtype.Text
	SpecialPatientType pgtype.Text
	NeedsCompanion     bool
	CompanionName      pgtype.Text
	ReferralOrigin     pgtype.Text
}

type OperationsAdmissionGuarantor struct {
	ID            pgtype.UUID
	AdmissionID   pgtype.UUID
	PayerID       pgtype.UUID
	PolicyNumber  pgtype.Text
	GuarantorName pgtype.Text
	Sequence      int16
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
}

type OperationsCounter struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	MerchantID   pgtype.UUID
	QueueType    string
	DepartmentID pgtype.UUID
	Code         string
	Name         pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	RowVersion   int32
}

type OperationsPhysicianSchedule struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	MerchantID    pgtype.UUID
	PhysicianID   pgtype.UUID
	DepartmentID  pgtype.UUID
	DayOfWeek     int16
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	SlotQuota     int32
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	DeletedAt     pgtype.Timestamptz
	DeletedBy     pgtype.UUID
	RowVersion    int32
}

type OperationsQueue struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	MerchantID   pgtype.UUID
	QueueType    string
	DepartmentID pgtype.UUID
	PersonID     pgtype.UUID
	AdmissionID  pgtype.UUID
	CounterID    pgtype.UUID
	QueueNumber  string
	Status       string
	CalledAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	RowVersion   int32
}

type OperationsQueueBoard struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	MerchantID            pgtype.UUID
	QueueType             string
	DepartmentID          pgtype.UUID
	QueueNumber           string
	Status                string
	CalledAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	PersonID              pgtype.UUID
	PersonFullName        string
	PersonMedicalRecordNo pgtype.Text
	PersonBirthDate       pgtype.Date
	AdmissionID           pgtype.UUID
	AdmissionVisitNo      pgtype.Text
	PhysicianID           pgtype.UUID
	PhysicianFullName     pgtype.Text
	PhysicianSpecialty    pgtype.Text
	PersonPhotoUrl        pgtype.Text
	PhysicianPhotoUrl     pgtype.Text
	CounterID             pgtype.UUID
	CounterCode           pgtype.Text
	CounterName           pgtype.Text
}

type OperationsQueueStatusHistory struct {
	ID         pgtype.UUID
	QueueID    pgtype.UUID
	CounterID  pgtype.UUID
	FromStatus pgtype.Text
	ToStatus   string
	ChangedBy  pgtype.UUID
	ChangedAt  pgtype.Timestamptz
}

type TerminologyCodeSystem struct {
	ID        pgtype.UUID
	SystemUri string
	Name      string
	Version   string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type TerminologyConcept struct {
	ID           pgtype.UUID
	CodeSystemID pgtype.UUID
	Code         string
	Display      string
	Definition   pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type TerminologyConceptHierarchy struct {
	ParentConceptID  pgtype.UUID
	ChildConceptID   pgtype.UUID
	RelationshipType string
}

type PlatformAdminUser struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	FullName     string
	PasswordHash string
	IsActive     bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.UUID
	RowVersion   int32
}

type PlatformPermission struct {
	ID          pgtype.UUID
	Code        string
	Description string
	Module      string
}

type PlatformRole struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
	DeletedAt   pgtype.Timestamptz
	DeletedBy   pgtype.UUID
	RowVersion  int32
}

type PlatformRolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type PlatformAdminUserRole struct {
	AdminUserID pgtype.UUID
	RoleID      pgtype.UUID
}

type PlatformAdminRefreshToken struct {
	ID          pgtype.UUID
	AdminUserID pgtype.UUID
	DeviceID    string
	DeviceLabel string
	TokenHash   string
	IssuedAt    pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedIp   netip.Addr
}

type PlatformImpersonationSession struct {
	ID              pgtype.UUID
	AdminUserID     pgtype.UUID
	TargetUserID    pgtype.UUID
	TargetCompanyID pgtype.UUID
	Reason          string
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	StartedIp       netip.Addr
}
