// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO core.role_permission (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const addUserMerchantRole = `-- name: AddUserMerchantRole :one
INSERT INTO core.user_merchant_role (user_id, merchant_id, role_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, merchant_id, role_id) DO NOTHING
RETURNING id, user_id, merchant_id, role_id, created_at, created_by
`

type AddUserMerchantRoleParams struct {
	UserID     pgtype.UUID
	MerchantID pgtype.UUID
	RoleID     pgtype.UUID
	CreatedBy  pgtype.UUID
}

func (q *Queries) AddUserMerchantRole(ctx context.Context, arg AddUserMerchantRoleParams) (CoreUserMerchantRole, error) {
	row := q.db.QueryRow(ctx, addUserMerchantRole,
		arg.UserID,
		arg.MerchantID,
		arg.RoleID,
		arg.CreatedBy,
	)
	var i CoreUserMerchantRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const clearAppUserMFASecret = `-- name: ClearAppUserMFASecret :exec
UPDATE core.app_user
SET mfa_secret = NULL, updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type ClearAppUserMFASecretParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) ClearAppUserMFASecret(ctx context.Context, arg ClearAppUserMFASecretParams) error {
	_, err := q.db.Exec(ctx, clearAppUserMFASecret, arg.ID, arg.UpdatedBy)
	return err
}

const clearAppUserPin = `-- name: ClearAppUserPin :exec
UPDATE core.app_user
SET pin_hash = NULL, updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type ClearAppUserPinParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) ClearAppUserPin(ctx context.Context, arg ClearAppUserPinParams) error {
	_, err := q.db.Exec(ctx, clearAppUserPin, arg.ID, arg.UpdatedBy)
	return err
}

const createAppUser = `-- name: CreateAppUser :one

INSERT INTO core.app_user (company_id, person_id, username, email, phone, password_hash, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, company_id, person_id, username, email, password_hash, mfa_secret, is_active, last_login_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, pin_hash, phone
`

type CreateAppUserParams struct {
	CompanyID    pgtype.UUID
	PersonID     pgtype.UUID
	Username     string
	Email        pgtype.Text
	Phone        pgtype.Text
	PasswordHash string
	CreatedBy    pgtype.UUID
}

// internal/db/queries/rbac.sql
// core.app_user, core.permission, core.role, core.role_permission, core.user_merchant_role
// (docs/07-core-ddl.md §2 "RBAC")
func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (CoreAppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.CompanyID,
		arg.PersonID,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.CreatedBy,
	)
	var i CoreAppUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.PinHash,
		&i.Phone,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO core.permission (code, description, module)
VALUES ($1, $2, $3)
RETURNING id, code, description, module
`

type CreatePermissionParams struct {
	Code        string
	Description string
	Module      string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (CorePermission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Code, arg.Description, arg.Module)
	var i CorePermission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO core.role (company_id, name, description, is_system, requires_physician_data, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, company_id, name, description, is_system, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, requires_physician_data
`

type CreateRoleParams struct {
	CompanyID             pgtype.UUID
	Name                  string
	Description           pgtype.Text
	IsSystem              bool
	RequiresPhysicianData bool
	CreatedBy             pgtype.UUID
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CoreRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.RequiresPhysicianData,
		arg.CreatedBy,
	)
	var i CoreRole
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.RequiresPhysicianData,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM core.permission WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getAppUserByID = `-- name: GetAppUserByID :one
SELECT id, company_id, person_id, username, email, password_hash, mfa_secret, is_active, last_login_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, pin_hash, phone FROM core.app_user WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppUserByID(ctx context.Context, id pgtype.UUID) (CoreAppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByID, id)
	var i CoreAppUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.PinHash,
		&i.Phone,
	)
	return i, err
}

const getAppUserByUsername = `-- name: GetAppUserByUsername :one
SELECT id, company_id, person_id, username, email, password_hash, mfa_secret, is_active, last_login_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, pin_hash, phone FROM core.app_user WHERE company_id = $1 AND username = $2 AND deleted_at IS NULL
`

type GetAppUserByUsernameParams struct {
	CompanyID pgtype.UUID
	Username  string
}

func (q *Queries) GetAppUserByUsername(ctx context.Context, arg GetAppUserByUsernameParams) (CoreAppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByUsername, arg.CompanyID, arg.Username)
	var i CoreAppUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.PinHash,
		&i.Phone,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description, module FROM core.permission WHERE code = $1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (CorePermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i CorePermission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, company_id, name, description, is_system, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, requires_physician_data FROM core.role WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (CoreRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i CoreRole
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.RequiresPhysicianData,
	)
	return i, err
}

const getUserMerchantRoleByID = `-- name: GetUserMerchantRoleByID :one
SELECT id, user_id, merchant_id, role_id, created_at, created_by FROM core.user_merchant_role WHERE id = $1
`

func (q *Queries) GetUserMerchantRoleByID(ctx context.Context, id pgtype.UUID) (CoreUserMerchantRole, error) {
	row := q.db.QueryRow(ctx, getUserMerchantRoleByID, id)
	var i CoreUserMerchantRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAppUsersByCompany = `-- name: ListAppUsersByCompany :many
SELECT id, company_id, person_id, username, email, password_hash, mfa_secret, is_active, last_login_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, pin_hash, phone FROM core.app_user
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY username
LIMIT $2 OFFSET $3
`

type ListAppUsersByCompanyParams struct {
	CompanyID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAppUsersByCompany(ctx context.Context, arg ListAppUsersByCompanyParams) ([]CoreAppUser, error) {
	rows, err := q.db.Query(ctx, listAppUsersByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreAppUser{}
	for rows.Next() {
		var i CoreAppUser
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PersonID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.RowVersion,
			&i.PinHash,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionCodesByUserMerchant = `-- name: ListPermissionCodesByUserMerchant :many
SELECT DISTINCT p.code
FROM core.user_merchant_role umr
JOIN core.role r ON r.id = umr.role_id AND r.deleted_at IS NULL
JOIN core.role_permission rp ON rp.role_id = r.id
JOIN core.permission p ON p.id = rp.permission_id
WHERE umr.user_id = $1 AND umr.merchant_id = $2
ORDER BY p.code
`

type ListPermissionCodesByUserMerchantParams struct {
	UserID     pgtype.UUID
	MerchantID pgtype.UUID
}

// Effective permission codes for a user at a merchant (union across all
// their roles there) -- self-access endpoint for permission-driven frontend
// UI (nav/dashboard gating), since ListRolePermissions itself requires
// PermRoleManage and a regular user can't read their own role's permission
// list through it.
func (q *Queries) ListPermissionCodesByUserMerchant(ctx context.Context, arg ListPermissionCodesByUserMerchantParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionCodesByUserMerchant, arg.UserID, arg.MerchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, description, module FROM core.permission ORDER BY module, code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]CorePermission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorePermission{}
	for rows.Next() {
		var i CorePermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT p.id, p.code, p.description, p.module FROM core.permission p
JOIN core.role_permission rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.module, p.code
`

func (q *Queries) ListPermissionsByRole(ctx context.Context, roleID pgtype.UUID) ([]CorePermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorePermission{}
	for rows.Next() {
		var i CorePermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByCompany = `-- name: ListRolesByCompany :many
SELECT id, company_id, name, description, is_system, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, requires_physician_data FROM core.role
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListRolesByCompanyParams struct {
	CompanyID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListRolesByCompany(ctx context.Context, arg ListRolesByCompanyParams) ([]CoreRole, error) {
	rows, err := q.db.Query(ctx, listRolesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRole{}
	for rows.Next() {
		var i CoreRole
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.RowVersion,
			&i.RequiresPhysicianData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByUserMerchant = `-- name: ListRolesByUserMerchant :many
SELECT r.id, r.company_id, r.name, r.description, r.is_system, r.created_at, r.created_by, r.updated_at, r.updated_by, r.deleted_at, r.deleted_by, r.row_version, r.requires_physician_data FROM core.role r
JOIN core.user_merchant_role umr ON umr.role_id = r.id
WHERE umr.user_id = $1 AND umr.merchant_id = $2 AND r.deleted_at IS NULL
`

type ListRolesByUserMerchantParams struct {
	UserID     pgtype.UUID
	MerchantID pgtype.UUID
}

func (q *Queries) ListRolesByUserMerchant(ctx context.Context, arg ListRolesByUserMerchantParams) ([]CoreRole, error) {
	rows, err := q.db.Query(ctx, listRolesByUserMerchant, arg.UserID, arg.MerchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRole{}
	for rows.Next() {
		var i CoreRole
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.RowVersion,
			&i.RequiresPhysicianData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMerchantRolesByUser = `-- name: ListUserMerchantRolesByUser :many
SELECT id, user_id, merchant_id, role_id, created_at, created_by FROM core.user_merchant_role WHERE user_id = $1
`

func (q *Queries) ListUserMerchantRolesByUser(ctx context.Context, userID pgtype.UUID) ([]CoreUserMerchantRole, error) {
	rows, err := q.db.Query(ctx, listUserMerchantRolesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUserMerchantRole{}
	for rows.Next() {
		var i CoreUserMerchantRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.RoleID,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM core.role_permission WHERE role_id = $1 AND permission_id = $2
`

type RemoveRolePermissionParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const removeUserMerchantRole = `-- name: RemoveUserMerchantRole :exec
DELETE FROM core.user_merchant_role WHERE id = $1
`

func (q *Queries) RemoveUserMerchantRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeUserMerchantRole, id)
	return err
}

const setAppUserMFASecret = `-- name: SetAppUserMFASecret :exec
UPDATE core.app_user
SET mfa_secret = $2, updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
`

type SetAppUserMFASecretParams struct {
	ID        pgtype.UUID
	MfaSecret pgtype.Text
	UpdatedBy pgtype.UUID
}

func (q *Queries) SetAppUserMFASecret(ctx context.Context, arg SetAppUserMFASecretParams) error {
	_, err := q.db.Exec(ctx, setAppUserMFASecret, arg.ID, arg.MfaSecret, arg.UpdatedBy)
	return err
}

const setAppUserPin = `-- name: SetAppUserPin :exec
UPDATE core.app_user
SET pin_hash = $2, updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
`

type SetAppUserPinParams struct {
	ID        pgtype.UUID
	PinHash   pgtype.Text
	UpdatedBy pgtype.UUID
}

func (q *Queries) SetAppUserPin(ctx context.Context, arg SetAppUserPinParams) error {
	_, err := q.db.Exec(ctx, setAppUserPin, arg.ID, arg.PinHash, arg.UpdatedBy)
	return err
}

const softDeleteAppUser = `-- name: SoftDeleteAppUser :exec
UPDATE core.app_user
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteAppUserParams struct {
	ID        pgtype.UUID
	DeletedBy pgtype.UUID
}

func (q *Queries) SoftDeleteAppUser(ctx context.Context, arg SoftDeleteAppUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteAppUser, arg.ID, arg.DeletedBy)
	return err
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE core.role
SET deleted_at = now(), deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL AND NOT is_system
`

type SoftDeleteRoleParams struct {
	ID        pgtype.UUID
	DeletedBy pgtype.UUID
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.Exec(ctx, softDeleteRole, arg.ID, arg.DeletedBy)
	return err
}

const touchAppUserLastLogin = `-- name: TouchAppUserLastLogin :exec
UPDATE core.app_user
SET last_login_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchAppUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAppUserLastLogin, id)
	return err
}

const updateAppUser = `-- name: UpdateAppUser :one
UPDATE core.app_user
SET person_id = $2, email = $3, is_active = $4, updated_by = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, company_id, person_id, username, email, password_hash, mfa_secret, is_active, last_login_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, pin_hash, phone
`

type UpdateAppUserParams struct {
	ID        pgtype.UUID
	PersonID  pgtype.UUID
	Email     pgtype.Text
	IsActive  bool
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateAppUser(ctx context.Context, arg UpdateAppUserParams) (CoreAppUser, error) {
	row := q.db.QueryRow(ctx, updateAppUser,
		arg.ID,
		arg.PersonID,
		arg.Email,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i CoreAppUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.PinHash,
		&i.Phone,
	)
	return i, err
}

const updateAppUserPassword = `-- name: UpdateAppUserPassword :exec
UPDATE core.app_user
SET password_hash = $2, updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAppUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
	UpdatedBy    pgtype.UUID
}

func (q *Queries) UpdateAppUserPassword(ctx context.Context, arg UpdateAppUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAppUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedBy)
	return err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE core.permission
SET description = $2, module = $3
WHERE id = $1
RETURNING id, code, description, module
`

type UpdatePermissionParams struct {
	ID          pgtype.UUID
	Description string
	Module      string
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (CorePermission, error) {
	row := q.db.QueryRow(ctx, updatePermission, arg.ID, arg.Description, arg.Module)
	var i CorePermission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE core.role
SET name = $2, description = $3, requires_physician_data = $4, updated_by = $5
WHERE id = $1 AND deleted_at IS NULL AND NOT is_system
RETURNING id, company_id, name, description, is_system, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, requires_physician_data
`

type UpdateRoleParams struct {
	ID                    pgtype.UUID
	Name                  string
	Description           pgtype.Text
	RequiresPhysicianData bool
	UpdatedBy             pgtype.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (CoreRole, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RequiresPhysicianData,
		arg.UpdatedBy,
	)
	var i CoreRole
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.RequiresPhysicianData,
	)
	return i, err
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM core.user_merchant_role umr
    JOIN core.role r ON r.id = umr.role_id AND r.deleted_at IS NULL
    JOIN core.role_permission rp ON rp.role_id = r.id
    JOIN core.permission p ON p.id = rp.permission_id
    WHERE umr.user_id = $1 AND umr.merchant_id = $2 AND p.code = $3
) AS has_permission
`

type UserHasPermissionParams struct {
	UserID     pgtype.UUID
	MerchantID pgtype.UUID
	Code       string
}

func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPermission, arg.UserID, arg.MerchantID, arg.Code)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
