// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyWithID = `-- name: CreateCompanyWithID :one
INSERT INTO core.company (id, code, name, created_by, updated_by)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, code, name, is_active, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, row_version, max_concurrent_sessions
`

type CreateCompanyWithIDParams struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateCompanyWithID(ctx context.Context, arg CreateCompanyWithIDParams) (CoreCompany, error) {
	row := q.db.QueryRow(ctx, createCompanyWithID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.CreatedBy,
	)
	var i CoreCompany
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.RowVersion,
		&i.MaxConcurrentSessions,
	)
	return i, err
}


const createUserCompanyRole = `-- name: CreateUserCompanyRole :one
INSERT INTO core.user_company_role (user_id, company_id, role_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, company_id, role_id) DO NOTHING
RETURNING id, user_id, company_id, role_id, created_at, created_by
`

type CreateUserCompanyRoleParams struct {
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
	RoleID    pgtype.UUID
	CreatedBy pgtype.UUID
}

type CoreUserCompanyRole struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateUserCompanyRole(ctx context.Context, arg CreateUserCompanyRoleParams) (CoreUserCompanyRole, error) {
	row := q.db.QueryRow(ctx, createUserCompanyRole,
		arg.UserID,
		arg.CompanyID,
		arg.RoleID,
		arg.CreatedBy,
	)
	var i CoreUserCompanyRole
	err := row.Scan(&i.ID, &i.UserID, &i.CompanyID, &i.RoleID, &i.CreatedAt, &i.CreatedBy)
	return i, err
}

const userHasCompanyLevelPermission = `-- name: UserHasCompanyLevelPermission :one
SELECT core.user_has_company_level_permission($1, $2, $3)
`

type UserHasCompanyLevelPermissionParams struct {
	UserID    pgtype.UUID
	CompanyID pgtype.UUID
	Codes     []string
}

func (q *Queries) UserHasCompanyLevelPermission(ctx context.Context, arg UserHasCompanyLevelPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasCompanyLevelPermission, arg.UserID, arg.CompanyID, arg.Codes)
	var has bool
	err := row.Scan(&has)
	return has, err
}

const listUserCompanyRoles = `-- name: ListUserCompanyRoles :many
SELECT id, user_id, company_id, role_id, created_at, created_by FROM core.user_company_role WHERE user_id = $1
`

func (q *Queries) ListUserCompanyRoles(ctx context.Context, userID pgtype.UUID) ([]CoreUserCompanyRole, error) {
	rows, err := q.db.Query(ctx, listUserCompanyRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreUserCompanyRole{}
	for rows.Next() {
		var i CoreUserCompanyRole
		if err := rows.Scan(&i.ID, &i.UserID, &i.CompanyID, &i.RoleID, &i.CreatedAt, &i.CreatedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
