// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_matrix.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoleWidget = `-- name: AddRoleWidget :exec
INSERT INTO core.role_widget (role_id, widget_key, visible) VALUES ($1, $2, $3)
`

type AddRoleWidgetParams struct {
	RoleID    pgtype.UUID
	WidgetKey string
	Visible   bool
}

func (q *Queries) AddRoleWidget(ctx context.Context, arg AddRoleWidgetParams) error {
	_, err := q.db.Exec(ctx, addRoleWidget, arg.RoleID, arg.WidgetKey, arg.Visible)
	return err
}

const copyRolePermissions = `-- name: CopyRolePermissions :execrows
INSERT INTO core.role_permission (role_id, permission_id)
SELECT $1, permission_id FROM core.role_permission src WHERE src.role_id = $2
`

type CopyRolePermissionsParams struct {
	RoleID   pgtype.UUID
	RoleID_2 pgtype.UUID
}

func (q *Queries) CopyRolePermissions(ctx context.Context, arg CopyRolePermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyRolePermissions, arg.RoleID, arg.RoleID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyRoleWidgets = `-- name: CopyRoleWidgets :execrows
INSERT INTO core.role_widget (role_id, widget_key, visible)
SELECT $1, widget_key, visible FROM core.role_widget src WHERE src.role_id = $2
`

type CopyRoleWidgetsParams struct {
	RoleID   pgtype.UUID
	RoleID_2 pgtype.UUID
}

func (q *Queries) CopyRoleWidgets(ctx context.Context, arg CopyRoleWidgetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyRoleWidgets, arg.RoleID, arg.RoleID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissionsNotIn = `-- name: DeleteRolePermissionsNotIn :execrows
DELETE FROM core.role_permission WHERE role_id = $1 AND NOT (permission_id = ANY($2::uuid[]))
`

type DeleteRolePermissionsNotInParams struct {
	RoleID  pgtype.UUID
	Column2 []pgtype.UUID
}

func (q *Queries) DeleteRolePermissionsNotIn(ctx context.Context, arg DeleteRolePermissionsNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRolePermissionsNotIn, arg.RoleID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRoleWidgets = `-- name: DeleteRoleWidgets :execrows
DELETE FROM core.role_widget WHERE role_id = $1
`

func (q *Queries) DeleteRoleWidgets(ctx context.Context, roleID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoleWidgets, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLastRoleChange = `-- name: GetLastRoleChange :one
SELECT l.changed_at, l.reason, l.changes, p.full_name AS changed_by_name
FROM core.role_change_log l
LEFT JOIN core.app_user u ON u.id = l.changed_by
LEFT JOIN core.person p ON p.id = u.person_id
WHERE l.role_id = $1
ORDER BY l.changed_at DESC
LIMIT 1
`

type GetLastRoleChangeRow struct {
	ChangedAt     pgtype.Timestamptz
	Reason        string
	Changes       []byte
	ChangedByName pgtype.Text
}

func (q *Queries) GetLastRoleChange(ctx context.Context, roleID pgtype.UUID) (GetLastRoleChangeRow, error) {
	row := q.db.QueryRow(ctx, getLastRoleChange, roleID)
	var i GetLastRoleChangeRow
	err := row.Scan(
		&i.ChangedAt,
		&i.Reason,
		&i.Changes,
		&i.ChangedByName,
	)
	return i, err
}

const insertRoleChangeLog = `-- name: InsertRoleChangeLog :exec
INSERT INTO core.role_change_log (company_id, role_id, changed_by, reason, changes)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRoleChangeLogParams struct {
	CompanyID pgtype.UUID
	RoleID    pgtype.UUID
	ChangedBy pgtype.UUID
	Reason    string
	Changes   []byte
}

func (q *Queries) InsertRoleChangeLog(ctx context.Context, arg InsertRoleChangeLogParams) error {
	_, err := q.db.Exec(ctx, insertRoleChangeLog,
		arg.CompanyID,
		arg.RoleID,
		arg.ChangedBy,
		arg.Reason,
		arg.Changes,
	)
	return err
}

const listPermissionCodesByIDs = `-- name: ListPermissionCodesByIDs :many
SELECT code FROM core.permission WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListPermissionCodesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionCodesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleChanges = `-- name: ListRoleChanges :many
SELECT l.changed_at, l.reason, l.changes, p.full_name AS changed_by_name
FROM core.role_change_log l
LEFT JOIN core.app_user u ON u.id = l.changed_by
LEFT JOIN core.person p ON p.id = u.person_id
WHERE l.role_id = $1
ORDER BY l.changed_at DESC
LIMIT $2
`

type ListRoleChangesParams struct {
	RoleID pgtype.UUID
	Limit  int32
}

type ListRoleChangesRow struct {
	ChangedAt     pgtype.Timestamptz
	Reason        string
	Changes       []byte
	ChangedByName pgtype.Text
}

func (q *Queries) ListRoleChanges(ctx context.Context, arg ListRoleChangesParams) ([]ListRoleChangesRow, error) {
	rows, err := q.db.Query(ctx, listRoleChanges, arg.RoleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleChangesRow{}
	for rows.Next() {
		var i ListRoleChangesRow
		if err := rows.Scan(
			&i.ChangedAt,
			&i.Reason,
			&i.Changes,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleWidgets = `-- name: ListRoleWidgets :many
SELECT role_id, widget_key, visible
FROM core.role_widget
WHERE role_id = $1
`

func (q *Queries) ListRoleWidgets(ctx context.Context, roleID pgtype.UUID) ([]CoreRoleWidget, error) {
	rows, err := q.db.Query(ctx, listRoleWidgets, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreRoleWidget{}
	for rows.Next() {
		var i CoreRoleWidget
		if err := rows.Scan(&i.RoleID, &i.WidgetKey, &i.Visible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithCounts = `-- name: ListRolesWithCounts :many
SELECT r.id, r.company_id, r.name, r.description, r.is_system, r.requires_physician_data,
       COALESCE(p.perm_count, 0)::bigint AS permission_count,
       COALESCE(u.user_count, 0)::bigint AS user_count
FROM core.role r
LEFT JOIN (
    SELECT role_id, COUNT(*) AS perm_count FROM core.role_permission GROUP BY role_id
) p ON p.role_id = r.id
LEFT JOIN (
    SELECT role_id, COUNT(DISTINCT user_id) AS user_count
    FROM core.user_merchant_role GROUP BY role_id
) u ON u.role_id = r.id
WHERE r.company_id = $1 AND r.deleted_at IS NULL
ORDER BY r.name
LIMIT $2 OFFSET $3
`

type ListRolesWithCountsParams struct {
	CompanyID pgtype.UUID
	Limit     int32
	Offset    int32
}

type ListRolesWithCountsRow struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	Name                  string
	Description           pgtype.Text
	IsSystem              bool
	RequiresPhysicianData bool
	PermissionCount       int64
	UserCount             int64
}

func (q *Queries) ListRolesWithCounts(ctx context.Context, arg ListRolesWithCountsParams) ([]ListRolesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithCounts, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesWithCountsRow{}
	for rows.Next() {
		var i ListRolesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.RequiresPhysicianData,
			&i.PermissionCount,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
